version: '3'
services:
  frontend:
    build: ./frontend
    container_name: filmsquad_frontend
    stdin_open: true
    ports:
      - '80:80'
    networks:
      - filmsquad
  backend:
    build: ./backend
    container_name: filmsquad_backend
    ports:
      - '8080:8080'
    depends_on:
      - mongo
    networks:
      - filmsquad
  mongo:
    image: mongo
    container_name: filmsquad_mongo
    ports:
      - '27017:27017'
    networks:
      - filmsquad
    volumes:
      - mongo-data:/data/db
  mongo-express:
    image: mongo-express
    container_name: filmsquad_mongo_express
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin
      ME_CONFIG_MONGODB_SERVER: mongo
    ports:
      - '8081:8081'
    depends_on:
      - mongo
    networks:
      - filmsquad
networks:
  filmsquad:
    driver: bridge
volumes:
  mongo-data:
    driver: local
